source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ZLCategory_Example', :exclusive => true do
  pod "ZLCategory", :path => "../"
end

target 'ZLCategory_Tests', :exclusive => true do
  pod "ZLCategory", :path => "../"

  
end
